Batchmanifest.create!(filename: "clients.csv", filetype: "clients")
Batchmanifest.create!(filename: "locations.csv", filetype: "locations")
Batchmanifest.create!(filename: "categories.csv", filetype: "categories")
Batchmanifest.create!(filename: "services.csv", filetype: "services")
Batchmanifest.create!(filename: "pricings.csv", filetype: "pricings")
Batchmanifest.create!(filename: "employees.csv", filetype: "employees")
Batchmanifest.create!(filename: "addonmappings.csv", filetype: "add_ons_mappings")
Batchmanifest.create!(filename: "breedgroups.csv", filetype: "breedgroups")
Batchmanifest.create!(filename: "pets.csv", filetype: "pets")
Batchmanifest.create!(filename: "appointments.zip", filetype: "appointments")
Batchmanifest.create!(filename: "appointments.csv", filetype: "appointments")
Batchmanifest.create!(filename: "appointment_services.csv", filetype: "appointment_services")
Batchmanifest.create!(filename: "appointment_statuses.csv", filetype: "appointment_statuses")
Batchmanifest.create!(filename: "appointment_manifest.csv", filetype: "appointment_manifest")
Batchmanifest.create!(filename: "inventories.zip", filetype: "inventory")

puts "Batch manifest created"
