require 'faker'


Membership.create!(
  membership_id: 1,
  membership_name: "10% Everything",
  description: "10% off of all products and services",
  registration_fee_amount: 0,
  cancellation_fee_amount: 10,
  price: 20,
  period_size: 12,
  billing_cycle_type: "date_of_sale",
  payment_type: "monthly",
  benefit_name: "10% discount",
  location_id: 1,
  benefit_id: 1,
  benefit_type: "discount",
  benefit_discount_type: "percentage",
  benefit_value: 10,
  benefit_limit: 0,
  eligible_for_all_services: true,
  eligible_for_all_products: true
)
Membership.create!(
  membership_id: 2,
  membership_name: "10% Everything",
  description: "10% off of all products and services",
  registration_fee_amount: 0,
  cancellation_fee_amount: 10,
  price: 20,
  period_size: 12,
  billing_cycle_type: "date_of_sale",
  payment_type: "monthly",
  benefit_name: "10% discount",
  location_id: 2,
  benefit_id: 2,
  benefit_type: "discount",
  benefit_discount_type: "percentage",
  benefit_value: 10,
  benefit_limit: 0,
  eligible_for_all_services: true,
  eligible_for_all_products: true
)
Membership.create!(
  membership_id: 3,
  membership_name: "10% Everything",
  description: "10% off of all products and services",
  registration_fee_amount: 0,
  cancellation_fee_amount: 10,
  price: 20,
  period_size: 12,
  billing_cycle_type: "date_of_sale",
  payment_type: "monthly",
  benefit_name: "10% discount",
  location_id: 3,
  benefit_id: 3,
  benefit_type: "discount",
  benefit_discount_type: "percentage",
  benefit_value: 10,
  benefit_limit: 0,
  eligible_for_all_services: true,
  eligible_for_all_products: true
)
Membership.create!(
  membership_id: 4,
  membership_name: "Free Add-ons",
  description: "Unlimited Add-ons",
  registration_fee_amount: 0,
  cancellation_fee_amount: 10,
  price: 37.5,
  period_size: 12,
  billing_cycle_type: "date_of_sale",
  payment_type: "monthly",
  benefit_name: "Unlimted free add-ons",
  location_id: 1,
  benefit_id: 4,
  benefit_type: "full",
  benefit_value: 0,
  benefit_limit: 0,
  eligible_for_all_services: false,
  eligible_for_all_products: false,
  service_id: 7
)
Membership.create!(
  membership_id: 5,
  membership_name: "Free Add-ons",
  description: "Unlimited Add-ons",
  registration_fee_amount: 0,
  cancellation_fee_amount: 10,
  price: 37.5,
  period_size: 12,
  billing_cycle_type: "date_of_sale",
  payment_type: "monthly",
  benefit_name: "Unlimted free add-ons",
  location_id: 2,
  benefit_id: 5,
  benefit_type: "full",
  benefit_value: 0,
  benefit_limit: 0,
  eligible_for_all_services: false,
  eligible_for_all_products: false,
  service_id: 7
)
Membership.create!(
  membership_id: 6,
  membership_name: "Free Add-ons",
  description: "Unlimited Add-ons",
  registration_fee_amount: 0,
  cancellation_fee_amount: 10,
  price: 37.5,
  period_size: 12,
  billing_cycle_type: "date_of_sale",
  payment_type: "monthly",
  benefit_name: "Unlimted free add-ons",
  location_id: 3,
  benefit_id: 6,
  benefit_type: "full",
  benefit_value: 0,
  benefit_limit: 0,
  eligible_for_all_services: false,
  eligible_for_all_products: false,
  service_id: 7
)

puts "Memberships created"
