require 'faker'

Salonpricing.create!(service_id: 1, location_id: 1, employee_id: nil, price: 12, deleted: false)
Salonpricing.create!(service_id: 2, location_id: 1, employee_id: nil, price: 32.50, deleted: false)
Salonpricing.create!(service_id: 3, location_id: 1, employee_id: nil, price: 45, deleted: false)
Salonpricing.create!(service_id: 4, location_id: 1, employee_id: nil, price: 49.99, deleted: false)
Salonpricing.create!(service_id: 5, location_id: 1, employee_id: nil, price: 80, deleted: false)
Salonpricing.create!(service_id: 6, location_id: 1, employee_id: nil, price: 99.99, deleted: false)
Salonpricing.create!(service_id: 7, location_id: 1, employee_id: nil, price: 15, deleted: false)

Salonpricing.create!(service_id: 1, location_id: 2, employee_id: nil, price: 12, deleted: false)
Salonpricing.create!(service_id: 2, location_id: 2, employee_id: nil, price: 32.50, deleted: false)
Salonpricing.create!(service_id: 3, location_id: 2, employee_id: nil, price: 45, deleted: false)
Salonpricing.create!(service_id: 4, location_id: 2, employee_id: nil, price: 49.99, deleted: false)
Salonpricing.create!(service_id: 5, location_id: 2, employee_id: nil, price: 80, deleted: false)
Salonpricing.create!(service_id: 6, location_id: 2, employee_id: nil, price: 99.99, deleted: false)
Salonpricing.create!(service_id: 7, location_id: 2, employee_id: nil, price: 15, deleted: false)

Salonpricing.create!(service_id: 1, location_id: 3, employee_id: nil, price: 12, deleted: false)
Salonpricing.create!(service_id: 2, location_id: 3, employee_id: nil, price: 32.50, deleted: false)
Salonpricing.create!(service_id: 3, location_id: 3, employee_id: nil, price: 45, deleted: false)
Salonpricing.create!(service_id: 4, location_id: 3, employee_id: nil, price: 49.99, deleted: false)
Salonpricing.create!(service_id: 5, location_id: 3, employee_id: nil, price: 80, deleted: false)
Salonpricing.create!(service_id: 7, location_id: 3, employee_id: nil, price: 15, deleted: false)

Salonpricing.create!(service_id: 1, location_id: 4, employee_id: nil, price: 12, deleted: false)
Salonpricing.create!(service_id: 2, location_id: 4, employee_id: nil, price: 32.50, deleted: false)
Salonpricing.create!(service_id: 3, location_id: 4, employee_id: nil, price: 45, deleted: false)
Salonpricing.create!(service_id: 4, location_id: 4, employee_id: nil, price: 49.99, deleted: false)
Salonpricing.create!(service_id: 5, location_id: 4, employee_id: nil, price: 80, deleted: false)
Salonpricing.create!(service_id: 6, location_id: 4, employee_id: nil, price: 99.99, deleted: false)
Salonpricing.create!(service_id: 7, location_id: 4, employee_id: nil, price: 15, deleted: false)

Salonpricing.create!(service_id: 1, location_id: 5, employee_id: nil, price: 12, deleted: false)
Salonpricing.create!(service_id: 2, location_id: 5, employee_id: nil, price: 32.50, deleted: false)
Salonpricing.create!(service_id: 3, location_id: 5, employee_id: nil, price: 45, deleted: false)
Salonpricing.create!(service_id: 7, location_id: 5, employee_id: nil, price: 15, deleted: false)

Salonpricing.create!(service_id: 1, location_id: 6, employee_id: nil, price: 12, deleted: false)
Salonpricing.create!(service_id: 2, location_id: 6, employee_id: nil, price: 32.50, deleted: false)
Salonpricing.create!(service_id: 3, location_id: 6, employee_id: nil, price: 45, deleted: false)
Salonpricing.create!(service_id: 4, location_id: 6, employee_id: nil, price: 49.99, deleted: false)
Salonpricing.create!(service_id: 5, location_id: 6, employee_id: nil, price: 80, deleted: false)
Salonpricing.create!(service_id: 6, location_id: 6, employee_id: nil, price: 99.99, deleted: false)
Salonpricing.create!(service_id: 7, location_id: 6, employee_id: nil, price: 15, deleted: false)

Salonpricing.create!(service_id: 1, location_id: 7, employee_id: nil, price: 12, deleted: false)
Salonpricing.create!(service_id: 2, location_id: 7, employee_id: nil, price: 32.50, deleted: false)
Salonpricing.create!(service_id: 3, location_id: 7, employee_id: nil, price: 45, deleted: false)
Salonpricing.create!(service_id: 4, location_id: 7, employee_id: nil, price: 49.99, deleted: false)
Salonpricing.create!(service_id: 5, location_id: 7, employee_id: nil, price: 80, deleted: false)
Salonpricing.create!(service_id: 6, location_id: 7, employee_id: nil, price: 99.99, deleted: false)

Salonpricing.create!(service_id: 1, location_id: 8, employee_id: nil, price: 12, deleted: false)
Salonpricing.create!(service_id: 2, location_id: 8, employee_id: nil, price: 32.50, deleted: false)
Salonpricing.create!(service_id: 3, location_id: 8, employee_id: nil, price: 45, deleted: false)
Salonpricing.create!(service_id: 4, location_id: 8, employee_id: nil, price: 49.99, deleted: false)
Salonpricing.create!(service_id: 5, location_id: 8, employee_id: nil, price: 80, deleted: false)
Salonpricing.create!(service_id: 6, location_id: 8, employee_id: nil, price: 99.99, deleted: false)
Salonpricing.create!(service_id: 7, location_id: 8, employee_id: nil, price: 15, deleted: false)

Salonpricing.create!(service_id: 1, location_id: 9, employee_id: nil, price: 12, deleted: false)
Salonpricing.create!(service_id: 2, location_id: 9, employee_id: nil, price: 32.50, deleted: false)
Salonpricing.create!(service_id: 3, location_id: 9, employee_id: nil, price: 45, deleted: false)
Salonpricing.create!(service_id: 4, location_id: 9, employee_id: nil, price: 49.99, deleted: false)
Salonpricing.create!(service_id: 5, location_id: 9, employee_id: nil, price: 80, deleted: false)
Salonpricing.create!(service_id: 6, location_id: 9, employee_id: nil, price: 99.99, deleted: false)
Salonpricing.create!(service_id: 7, location_id: 9, employee_id: nil, price: 15, deleted: false)

Salonpricing.create!(service_id: 1, location_id: 0, employee_id: nil, price: 12, deleted: false)
Salonpricing.create!(service_id: 2, location_id: 0, employee_id: nil, price: 32.50, deleted: false)
Salonpricing.create!(service_id: 3, location_id: 0, employee_id: nil, price: 45, deleted: false)
Salonpricing.create!(service_id: 4, location_id: 0, employee_id: nil, price: 49.99, deleted: false)
Salonpricing.create!(service_id: 5, location_id: 0, employee_id: nil, price: 80, deleted: false)
Salonpricing.create!(service_id: 6, location_id: 0, employee_id: nil, price: 99.99, deleted: false)
Salonpricing.create!(service_id: 7, location_id: 0, employee_id: nil, price: 15, deleted: false)

puts "Pricing created"
