 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/petservices", type: :request do
  # Petservice. As you add validations to Petservice, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Petservice.create! valid_attributes
      get petservices_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      petservice = Petservice.create! valid_attributes
      get petservice_url(petservice)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_petservice_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      petservice = Petservice.create! valid_attributes
      get edit_petservice_url(petservice)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Petservice" do
        expect {
          post petservices_url, params: { petservice: valid_attributes }
        }.to change(Petservice, :count).by(1)
      end

      it "redirects to the created petservice" do
        post petservices_url, params: { petservice: valid_attributes }
        expect(response).to redirect_to(petservice_url(Petservice.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Petservice" do
        expect {
          post petservices_url, params: { petservice: invalid_attributes }
        }.to change(Petservice, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post petservices_url, params: { petservice: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested petservice" do
        petservice = Petservice.create! valid_attributes
        patch petservice_url(petservice), params: { petservice: new_attributes }
        petservice.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the petservice" do
        petservice = Petservice.create! valid_attributes
        patch petservice_url(petservice), params: { petservice: new_attributes }
        petservice.reload
        expect(response).to redirect_to(petservice_url(petservice))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        petservice = Petservice.create! valid_attributes
        patch petservice_url(petservice), params: { petservice: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested petservice" do
      petservice = Petservice.create! valid_attributes
      expect {
        delete petservice_url(petservice)
      }.to change(Petservice, :count).by(-1)
    end

    it "redirects to the petservices list" do
      petservice = Petservice.create! valid_attributes
      delete petservice_url(petservice)
      expect(response).to redirect_to(petservices_url)
    end
  end
end
