 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/salonservices", type: :request do
  # Salonservice. As you add validations to Salonservice, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Salonservice.create! valid_attributes
      get salonservices_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      salonservice = Salonservice.create! valid_attributes
      get salonservice_url(salonservice)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_salonservice_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      salonservice = Salonservice.create! valid_attributes
      get edit_salonservice_url(salonservice)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Salonservice" do
        expect {
          post salonservices_url, params: { salonservice: valid_attributes }
        }.to change(Salonservice, :count).by(1)
      end

      it "redirects to the created salonservice" do
        post salonservices_url, params: { salonservice: valid_attributes }
        expect(response).to redirect_to(salonservice_url(Salonservice.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Salonservice" do
        expect {
          post salonservices_url, params: { salonservice: invalid_attributes }
        }.to change(Salonservice, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post salonservices_url, params: { salonservice: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested salonservice" do
        salonservice = Salonservice.create! valid_attributes
        patch salonservice_url(salonservice), params: { salonservice: new_attributes }
        salonservice.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the salonservice" do
        salonservice = Salonservice.create! valid_attributes
        patch salonservice_url(salonservice), params: { salonservice: new_attributes }
        salonservice.reload
        expect(response).to redirect_to(salonservice_url(salonservice))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        salonservice = Salonservice.create! valid_attributes
        patch salonservice_url(salonservice), params: { salonservice: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested salonservice" do
      salonservice = Salonservice.create! valid_attributes
      expect {
        delete salonservice_url(salonservice)
      }.to change(Salonservice, :count).by(-1)
    end

    it "redirects to the salonservices list" do
      salonservice = Salonservice.create! valid_attributes
      delete salonservice_url(salonservice)
      expect(response).to redirect_to(salonservices_url)
    end
  end
end
