 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/saloncategories", type: :request do
  # Saloncategory. As you add validations to Saloncategory, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Saloncategory.create! valid_attributes
      get saloncategories_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      saloncategory = Saloncategory.create! valid_attributes
      get saloncategory_url(saloncategory)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_saloncategory_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      saloncategory = Saloncategory.create! valid_attributes
      get edit_saloncategory_url(saloncategory)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Saloncategory" do
        expect {
          post saloncategories_url, params: { saloncategory: valid_attributes }
        }.to change(Saloncategory, :count).by(1)
      end

      it "redirects to the created saloncategory" do
        post saloncategories_url, params: { saloncategory: valid_attributes }
        expect(response).to redirect_to(saloncategory_url(Saloncategory.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Saloncategory" do
        expect {
          post saloncategories_url, params: { saloncategory: invalid_attributes }
        }.to change(Saloncategory, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post saloncategories_url, params: { saloncategory: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested saloncategory" do
        saloncategory = Saloncategory.create! valid_attributes
        patch saloncategory_url(saloncategory), params: { saloncategory: new_attributes }
        saloncategory.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the saloncategory" do
        saloncategory = Saloncategory.create! valid_attributes
        patch saloncategory_url(saloncategory), params: { saloncategory: new_attributes }
        saloncategory.reload
        expect(response).to redirect_to(saloncategory_url(saloncategory))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        saloncategory = Saloncategory.create! valid_attributes
        patch saloncategory_url(saloncategory), params: { saloncategory: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested saloncategory" do
      saloncategory = Saloncategory.create! valid_attributes
      expect {
        delete saloncategory_url(saloncategory)
      }.to change(Saloncategory, :count).by(-1)
    end

    it "redirects to the saloncategories list" do
      saloncategory = Saloncategory.create! valid_attributes
      delete saloncategory_url(saloncategory)
      expect(response).to redirect_to(saloncategories_url)
    end
  end
end
